
DEFAULT_DELAY = 0.3
DEFAULT_CONCURRENCY = 10
DEFAULT_TIMEOUT = 15
MAX_RETRIES_429 = 3
RETRY_BACKOFF_BASE = 3
DEFAULT_RATE_LIMIT = 2.0
HTTP_CONNECTOR_LIMIT = 50

RESULTS_DIR = "results"
COMBOLIST_DIR = "combolists"
OUTPUT_ENCODING = "utf-8"

MIN_COMBO_PARTS = 2
REQUIRED_FIELDS = ("email", "password")

PROGRESS_UPDATE_INTERVAL = 0.2
